### ISSUE TITLE
Small fix for python3

### ISSUE THREAD

**Issue by thatguywiththatname** [rshk/python-pcapng#10]
Line 108 in blocks.py is not compatible with py3: `interface_id = self._interfaces_id.next()`

It should be `interface_id = next(self._interfaces_id)` if it is to work with python3.

edit: I see in this Github repo this has already been fixed. It doesn't seem to have been pushed to PyPI though?

**Comment by rshk** [comment]
Ok, I just pushed 0.2 to pypi, should be fixed now. Not 100% sure about py3 support status though (looks like there might be other fixes needed), I opened #11 to check / make tests pass.

**Comment by rshk** [comment]
Btw, if you'd like to help with that, contributions are very welcome :)

**Comment by thatguywiththatname** [comment]
Ok thanks 👍 :)
