### ISSUE TITLE
use pip install python-pcapng has ValueError

### ISSUE THREAD

**Issue by newchenggong** [rshk/python-pcapng#12]
with open('file.pcap') as fp:
    scanner = FileScanner(fp)
    for block in scanner:
        pass

running: 
raise ValueError("File not starting with a proper section header") -- yield self._read_next_block()

**Comment by rshk** [comment]
Hi, it looks like you're trying to read a PCAP file, rather than the newer PCAP-ng format which this library supports..

**Comment by rshk** [comment]
I'm closing this issue for now; let me know if you still have problems (if that was indeed a pcap-ng file)

**Comment by NewMai** [comment]
I have encountered the same problem as you, is anyone has any solution for that?
