### ISSUE TITLE
How to parse beacon packet

### ISSUE THREAD

**Issue by alchimia** [rshk/python-pcapng#17]
Hi guys,
i need to parse beacon packets and i want to know how to do. For example, i want to understand how to get [something like this](https://s33.postimg.org/lfsm198vz/Schermata_2017-11-23_alle_16.56.57.png) or [something like this](https://s33.postimg.org/lfsm198vz/Schermata_2017-11-23_alle_16.56.57.png). How can i do with python-pcapng? 

I can't see an example starting from a pcap file!

**Comment by rshk** [comment]
Hi @alchimia,

to do what you're describing, you'll need to use another library to parse the *contents* of the packet.

What python-pcapng does is simply parsing the pcapng file, which contains the **raw** packet data (inside `EnhancedPacket` blocks). You can use a library such as [scapy](http://www.secdev.org/projects/scapy/) to parse the data contained in the `packet_data` attribute of `EnhancedPacket` or `SimplePacket` blocks to access the information about (among other) the 802.11 protocol packet.

roughly, this should do:

```
from pcapng import FileScanner
from pcapng.blocks import EnhancedPacket, Packet, SimplePacket

PACKET_TYPES = EnhancedPacket, Packet, SimplePacket

with open('/tmp/mycapture.pcap') as fp:
    scanner = FileScanner(fp)
    for block in scanner:
        if isinstance(block, PACKET_TYPES):
            pass # Load block.packet_data into Scapy, allows reading data out of it
```

I'm not 100% sure about what function you need to use to have Scapy parse the data in this case, but I definitely remember doing this in the past. This answer https://stackoverflow.com/a/27265766/148845 might give you some hints on how to proceed.

**Comment by alchimia** [comment]
Thank you for your reply, @rshk. The problem is that [scapy](http://www.secdev.org/projects/scapy/) is very slow, i need to make parsing in a constrained device, i need a faster library like [dpkt](https://github.com/kbandla/dpkt), but its documentation is very poor.
