### ISSUE TITLE
tests existing pcapng files

### ISSUE THREAD

**Issue by kartoch** [rshk/python-pcapng#4]
It would be great to have a test suite of raw pcapng files to read by the library and compare expected results:

* load files by URL and/or locally
* run each file
* report results

Is there any standard test suite for this ?

I found some files there:

http://wiki.wireshark.org/Development/PcapNg

**Comment by rshk** [comment]
@kartoch do you have any follow-up on this? did you find any other interesting pcapng file to test against?

otherwise, I'm going to close this

**Comment by kartoch** [comment]
@rshk you can close it, no news on my side.
