### ISSUE TITLE
Support for writing pcap-ng files

### ISSUE THREAD

**Issue by advornic** [rshk/python-pcapng#7]
The use case is rewriting the timestamp for each packet - the source being either a pcap or a pcap-ng file.

**Comment by rshk** [comment]
Makes sense. Are you willing to contribute to the write support (if so, I can give you some hints / guidance along the road).

**Comment by advornic** [comment]
Not sure if I will get round to this soon, but sure, some pointers are welcome.

**Comment by rshk** [comment]
@advornic I guess I can close this issue as there is no work to be done associated with it.. let me know if you decide to contribute to the project.
